before:
  hooks:
    - go mod download
builds:
  - gobinary: "go1.16rc1"
    binary: pcopy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
nfpms:
  -
    package_name: pcopy
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://heckel.io/pcopy
    maintainer: Philipp C. Heckel <philipp.heckel@gmail.com>
    description: Copy/paste across machines
    license: Apache 2.0
    formats:
      - deb
      - rpm
    suggests:
      - bash-completion
    bindir: /usr/bin
    empty_folders:
      - /etc/pcopy
      - /var/cache/pcopy
    contents:
      - src: config/pcopy.service
        dst: /lib/systemd/system/pcopy.service
      - src: /usr/bin/pcopy
        dst: /usr/bin/pcp
        type: symlink
      - src: /usr/bin/pcopy
        dst: /usr/bin/ppaste
        type: symlink
      - src: scripts/autocomplete_bash
        dst: /etc/bash_completion.d/pcopy
      - src: /etc/bash_completion.d/pcopy
        dst: /etc/bash_completion.d/pcp
        type: symlink
      - src: /etc/bash_completion.d/pcopy
        dst: /etc/bash_completion.d/ppaste
        type: symlink
    scripts:
      postinstall: "scripts/postinst.sh"
      postremove: "scripts/postrm.sh"
archives:
  - replacements:
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - dockerfile: Dockerfile
    ids:
      - pcopy
    image_templates:
      - "binwiederhier/pcopy:latest"
      - "binwiederhier/pcopy:{{ .Tag }}"
      - "binwiederhier/pcopy:v{{ .Major }}.{{ .Minor }}"