name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install go1.16
        run: go get golang.org/dl/go1.16rc1 && go1.16rc1 download
      - name: Run tests, formatting, vetting and linting
        run: make check
      - name: Run and upload coverage to codecov.io
        run: make coverage coverage-upload